// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Stay.Data;

#nullable disable

namespace Smart_Stay.Migrations
{
    [DbContext(typeof(SmartDbContext))]
    [Migration("20260824080750_AddDocumentUserId")]
    partial class AddDocumentUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smart_Stay.Models.Admin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("UserId");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("Smart_Stay.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("documentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("documentPath");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("document_type");

                    b.Property<int?>("ListingApplication")
                        .HasColumnType("int")
                        .HasColumnName("listingApplication");

                    b.Property<int?>("RentalApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("rentalApplicationID");

                    b.Property<DateOnly>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("upload_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("DocumentId");

                    b.HasIndex("ListingApplication");

                    b.HasIndex("RentalApplicationId");

                    b.HasIndex("UserId");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("Smart_Stay.Models.Landlord", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("verification_status");

                    b.HasKey("UserId");

                    b.ToTable("Landlord", (string)null);
                });

            modelBuilder.Entity("Smart_Stay.Models.ListingApplication", b =>
                {
                    b.Property<int>("ListingApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("listingApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingApplicationId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("adminID");

                    b.Property<DateOnly>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("application_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("application_status");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int")
                        .HasColumnName("LandlordID");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("propertyID");

                    b.HasKey("ListingApplicationId");

                    b.HasIndex("AdminId");

                    b.HasIndex("LandlordId");

                    b.HasIndex("PropertyId");

                    b.ToTable("ListingApplication", (string)null);
                });

            modelBuilder.Entity("Smart_Stay.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("propertyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int")
                        .HasColumnName("bathrooms");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int")
                        .HasColumnName("bedrooms");

                    b.Property<DateOnly>("DateListed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date_listed")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int")
                        .HasColumnName("landlordID");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("location");

                    b.Property<decimal>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("propertyType");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title");

                    b.HasKey("PropertyId")
                        .HasName("PK_Property");

                    b.HasIndex("LandlordId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Smart_Stay.Models.RentalApplication", b =>
                {
                    b.Property<int>("RentalApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rentalApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalApplicationId"));

                    b.Property<DateOnly>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("application_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("Id_Number");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int")
                        .HasColumnName("landlordID");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("propertyID");

                    b.Property<string>("RentalApplicationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rentalApplicationStatus");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenantID");

                    b.HasKey("RentalApplicationId");

                    b.HasIndex("LandlordId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.ToTable("rentalApplication", (string)null);
                });

            modelBuilder.Entity("Smart_Stay.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("propertyID");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint")
                        .HasColumnName("rating");

                    b.Property<DateOnly>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("reviewDate")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenantID");

                    b.HasKey("ReviewId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("Smart_Stay.Models.Tenant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Employed")
                        .HasColumnName("employment_status");

                    b.HasKey("UserId");

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("Smart_Stay.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateOnly>("DateRegistered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date_Registered")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phoneNo");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("surName");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Smart_Stay.Models.Admin", b =>
                {
                    b.HasOne("Smart_Stay.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Smart_Stay.Models.Admin", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Admin_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Stay.Models.Document", b =>
                {
                    b.HasOne("Smart_Stay.Models.ListingApplication", "ListingApplicationNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("ListingApplication")
                        .HasConstraintName("FK_Document_ListingApplication");

                    b.HasOne("Smart_Stay.Models.RentalApplication", "RentalApplication")
                        .WithMany("Documents")
                        .HasForeignKey("RentalApplicationId")
                        .HasConstraintName("FK_Document_rentalApplication");

                    b.HasOne("Smart_Stay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Document_User");

                    b.Navigation("ListingApplicationNavigation");

                    b.Navigation("RentalApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Stay.Models.Landlord", b =>
                {
                    b.HasOne("Smart_Stay.Models.User", "User")
                        .WithOne("Landlord")
                        .HasForeignKey("Smart_Stay.Models.Landlord", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Landlord_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Stay.Models.ListingApplication", b =>
                {
                    b.HasOne("Smart_Stay.Models.Admin", "Admin")
                        .WithMany("ListingApplications")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK_ListingApplication_Admin");

                    b.HasOne("Smart_Stay.Models.Landlord", "Landlord")
                        .WithMany("ListingApplications")
                        .HasForeignKey("LandlordId")
                        .HasConstraintName("FK_ListingApplication_Landlord");

                    b.HasOne("Smart_Stay.Models.Property", "Property")
                        .WithMany("ListingApplications")
                        .HasForeignKey("PropertyId")
                        .HasConstraintName("FK_ListingApplication_Property");

                    b.Navigation("Admin");

                    b.Navigation("Landlord");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Smart_Stay.Models.Property", b =>
                {
                    b.HasOne("Smart_Stay.Models.Landlord", "Landlord")
                        .WithMany("Properties")
                        .HasForeignKey("LandlordId")
                        .IsRequired()
                        .HasConstraintName("FK_Property_Landlord");

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("Smart_Stay.Models.RentalApplication", b =>
                {
                    b.HasOne("Smart_Stay.Models.Landlord", "Landlord")
                        .WithMany("RentalApplications")
                        .HasForeignKey("LandlordId")
                        .HasConstraintName("FK_rentalApplication_Landlord");

                    b.HasOne("Smart_Stay.Models.Property", "Property")
                        .WithMany("RentalApplications")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_rentalApplication_Property");

                    b.HasOne("Smart_Stay.Models.Tenant", "Tenant")
                        .WithMany("RentalApplications")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_rentalApplication_Tenant1");

                    b.Navigation("Landlord");

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Smart_Stay.Models.Review", b =>
                {
                    b.HasOne("Smart_Stay.Models.Property", "Property")
                        .WithMany("Reviews")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_review_Property");

                    b.HasOne("Smart_Stay.Models.Tenant", "Tenant")
                        .WithMany("Reviews")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_review_Tenant");

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Smart_Stay.Models.Tenant", b =>
                {
                    b.HasOne("Smart_Stay.Models.User", "User")
                        .WithOne("Tenant")
                        .HasForeignKey("Smart_Stay.Models.Tenant", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Tenant_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Stay.Models.Admin", b =>
                {
                    b.Navigation("ListingApplications");
                });

            modelBuilder.Entity("Smart_Stay.Models.Landlord", b =>
                {
                    b.Navigation("ListingApplications");

                    b.Navigation("Properties");

                    b.Navigation("RentalApplications");
                });

            modelBuilder.Entity("Smart_Stay.Models.ListingApplication", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Smart_Stay.Models.Property", b =>
                {
                    b.Navigation("ListingApplications");

                    b.Navigation("RentalApplications");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Smart_Stay.Models.RentalApplication", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Smart_Stay.Models.Tenant", b =>
                {
                    b.Navigation("RentalApplications");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Smart_Stay.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Landlord");

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
